import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import dashboardRouter from "./dashboard.js";
import productsRouter from "./products.js";
import categoriesRouter from "./categories.js";
import brandsRouter from "./brands.js";
import salesRouter from "./sales.js";
import purchasesRouter from "./purchases.js";
import customersRouter from "./customers.js";
import suppliersRouter from "./suppliers.js";
import usersRouter from "./users.js";
import expensesRouter from "./expenses.js";
import reportsRouter from "./reports.js";
import settingsRouter from "./settings.js";
import notificationsRouter from "./notifications.js";
import exportRouter from "./export.js";
import importRouter from "./import.js";
import uploadRouter from "./upload.js";
import telegramRouter from "./telegram.js";
import emailRouter from "./email.js";
import dbbackupRouter from "./dbbackup.js";
import ledgerRouter from "./ledger.js";
import priceHistoryRouter from "./price-history.js";
import paymentsRouter from "./payments.js";
import staffRouter from "./staff.js";
import staffLedgerRouter from "./staff-ledger.js";
import supplierProductsRouter from "./supplier-products.js";
import supplierLedgerRouter from "./supplier-ledger.js";
import productSuppliersRouter from "./product-suppliers.js";
import calendarRouter from "./calendar.js";
import stockAdjustmentsRouter from "./stock-adjustments.js";
import remindersRouter from "./reminders.js";
import monthsRouter from "./months.js";
import { authenticate, requirePermission } from "../lib/auth-middleware.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use(authenticate);
router.use("/dashboard", requirePermission("dashboard"), dashboardRouter);
router.use("/products", requirePermission("inventory"), productsRouter);
router.use("/categories", requirePermission("inventory"), categoriesRouter);
router.use("/brands", requirePermission("inventory"), brandsRouter);
router.use("/sales", requirePermission("sales"), salesRouter);
router.use("/purchases", requirePermission("purchases"), purchasesRouter);
router.use("/customers", requirePermission("customers"), customersRouter);
router.use("/customers", requirePermission("customers"), priceHistoryRouter);
router.use("/customers", requirePermission("customers"), ledgerRouter);
router.use("/payments", requirePermission("payments"), paymentsRouter);
router.use("/suppliers", requirePermission("suppliers"), suppliersRouter);
router.use("/suppliers", requirePermission("suppliers"), supplierProductsRouter);
router.use("/suppliers", requirePermission("suppliers"), supplierLedgerRouter);
router.use("/products", requirePermission("inventory"), productSuppliersRouter);
router.use("/staff", requirePermission("staff"), staffRouter);
router.use("/staff", requirePermission("staff"), staffLedgerRouter);
router.use("/calendar", requirePermission("settings"), calendarRouter);
router.use("/stock-adjustments", requirePermission("inventory"), stockAdjustmentsRouter);
router.use("/reminders", requirePermission("notifications"), remindersRouter);
router.use("/months", requirePermission("settings"), monthsRouter);
router.use("/users", requirePermission("users"), usersRouter);
router.use("/expenses", requirePermission("expenses"), expensesRouter);
router.use("/reports", requirePermission("reports"), reportsRouter);
router.use("/settings", requirePermission("settings"), settingsRouter);
router.use("/notifications", requirePermission("notifications"), notificationsRouter);
router.use("/export", requirePermission("settings"), exportRouter);
router.use("/import", requirePermission("settings"), importRouter);
router.use("/upload", requirePermission("inventory"), uploadRouter);
router.use("/telegram", requirePermission("settings"), telegramRouter);
router.use("/email", requirePermission("settings"), emailRouter);
router.use("/backup", requirePermission("settings"), dbbackupRouter);

export default router;
