import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import dashboardRouter from "./dashboard.js";
import productsRouter from "./products.js";
import categoriesRouter from "./categories.js";
import brandsRouter from "./brands.js";
import salesRouter from "./sales.js";
import purchasesRouter from "./purchases.js";
import customersRouter from "./customers.js";
import suppliersRouter from "./suppliers.js";
import usersRouter from "./users.js";
import expensesRouter from "./expenses.js";
import reportsRouter from "./reports.js";
import settingsRouter from "./settings.js";
import notificationsRouter from "./notifications.js";
import exportRouter from "./export.js";
import importRouter from "./import.js";
import uploadRouter from "./upload.js";
import telegramRouter from "./telegram.js";
import emailRouter from "./email.js";
import dbbackupRouter from "./dbbackup.js";
import ledgerRouter from "./ledger.js";
import priceHistoryRouter from "./price-history.js";
import paymentsRouter from "./payments.js";
import staffRouter from "./staff.js";
import staffLedgerRouter from "./staff-ledger.js";
import supplierProductsRouter from "./supplier-products.js";
import supplierLedgerRouter from "./supplier-ledger.js";
import productSuppliersRouter from "./product-suppliers.js";
import generalLedgerRouter from "./general-ledger.js";
import calendarRouter from "./calendar.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/dashboard", dashboardRouter);
router.use("/products", productsRouter);
router.use("/categories", categoriesRouter);
router.use("/brands", brandsRouter);
router.use("/sales", salesRouter);
router.use("/purchases", purchasesRouter);
router.use("/customers", customersRouter);
router.use("/customers", ledgerRouter);
router.use("/customers", priceHistoryRouter);
router.use("/payments", paymentsRouter);
router.use("/suppliers", suppliersRouter);
router.use("/suppliers", supplierProductsRouter);
router.use("/suppliers", supplierLedgerRouter);
router.use("/products", productSuppliersRouter);
router.use("/staff", staffRouter);
router.use("/staff", staffLedgerRouter);
router.use("/general-ledger", generalLedgerRouter);
router.use("/calendar", calendarRouter);
router.use("/users", usersRouter);
router.use("/expenses", expensesRouter);
router.use("/reports", reportsRouter);
router.use("/settings", settingsRouter);
router.use("/notifications", notificationsRouter);
router.use("/export", exportRouter);
router.use("/import", importRouter);
router.use("/upload", uploadRouter);
router.use("/telegram", telegramRouter);
router.use("/email", emailRouter);
router.use("/backup", dbbackupRouter);

export default router;
